/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('locations').del()
  await knex('locations').insert([
    {
      id: 1,
      name: 'Upper West Side',
      code: 'UWS',
      neighbours: 'UES, HK, MT',
      trainline: '',
    },
    {
      id: 2,
      name: 'Upper East Side',
      code: 'UES',
      neighbours: 'UWS, MT',
      trainline: '',
    },
    {
      id: 3,
      name: 'Hells Kitchen',
      code: 'HK',
      neighbours: 'UWS, MT, TD, GD, CH',
      trainline: '',
    },
    {
      id: 4,
      name: 'Theater District',
      code: 'TD',
      neighbours: 'HK, MT, GD',
      trainline: '',
    },
    {
      id: 5,
      name: 'Midtown',
      code: 'MT',
      neighbours: 'UES, UWS, HK, TD, GD, MH, KT, CH, KB, FI',
      trainline: '',
    },
    {
      id: 6,
      name: 'Garment District',
      code: 'GD',
      neighbours: 'HK, TD, MT, CH',
      trainline: '',
    },
    {
      id: 7,
      name: 'Murray Hill',
      code: 'MH',
      neighbours: 'MT, KB',
      trainline: '',
    },
    {
      id: 8,
      name: 'Chelsea',
      code: 'CH',
      neighbours: 'HK, GD, MT, KT, FI GR, GV, WV, MD',
      trainline: '',
    },
    {
      id: 9,
      name: 'Korea Town',
      code: '',
      neighbours: 'MT, CH',
      trainline: '',
    },
    {
      id: 10,
      name: 'Flatiron District',
      code: 'FD',
      neighbours: 'CH, MT, GR, KB',
      trainline: '',
    },
    {
      id: 11,
      name: 'Kips Bay',
      code: 'KB',
      neighbours: 'MT, MH, FI, GR, ST',
      trainline: '',
    },
    {
      id: 12,
      name: 'Gramercy',
      code: 'GR',
      neighbours: 'CH, FI, KB, ST, EV, GV',
      trainline: '',
    },
    {
      id: 13,
      name: 'Stuyvesant Town',
      code: 'ST',
      neighbours: 'GR, KB, EV, AC',
      trainline: '',
    },
    {
      id: 14,
      name: 'Meatpacking District',
      code: 'MD',
      neighbours: 'CH, WV',
      trainline: '',
    },
    {
      id: 15,
      name: 'West Village',
      code: 'WV',
      neighbours: 'MD, CH, GV, HS',
      trainline: '',
    },
    {
      id: 16,
      name: 'Greenwich Village',
      code: 'GV',
      neighbours: 'WV, CH, GR, EV, NH, SH, HS',
      trainline: '',
    },
    {
      id: 17,
      name: 'NoHo',
      code: 'NH',
      neighbours: 'GV, EV, NO, SH',
      trainline: '',
    },
    {
      id: 18,
      name: 'East Village',
      code: 'EV',
      neighbours: 'GV, GR, NH, AC, LES',
      trainline: '',
    },
    {
      id: 19,
      name: 'Alphabet City',
      code: 'AC',
      neighbours: 'ST, EV, LES',
      trainline: '',
    },
    {
      id: 20,
      name: 'Hudson Square',
      code: 'HS',
      neighbours: 'WV, GV, SH, TR',
      trainline: '',
    },
    {
      id: 21,
      name: 'SoHo',
      code: 'SH',
      neighbours: 'HS, GV, NO, NH, LI, TR',
      trainline: '',
    },
    {
      id: 22,
      name: 'Nolita',
      code: 'NO',
      neighbours: 'NH, SH, LI, LES',
      trainline: '',
    },
    {
      id: 23,
      name: 'Little Italy',
      code: 'LI',
      neighbours: 'SH, NO, LES, CT',
      trainline: '',
    },
    {
      id: 24,
      name: 'Lower East Side',
      code: 'LES',
      neighbours: 'EV, AC, NO, LI, CT, TBR',
      trainline: '',
    },
    {
      id: 25,
      name: 'Tribeca',
      code: 'TR',
      neighbours: 'HS, SH, CT, CC, FD, BPC',
      trainline: '',
    },
    {
      id: 26,
      name: 'Chinatown',
      code: 'CT',
      neighbours: 'LI, TR, LES, TBR, CC',
      trainline: '',
    },
    {
      id: 27,
      name: 'Civic Center',
      code: 'CC',
      neighbours: 'TR, CT, TBR, FD',
      trainline: '',
    },
    {
      id: 28,
      name: 'Two Bridges',
      code: 'TBR',
      neighbours: 'LES, CT, CC, FD',
      trainline: '',
    },
    {
      id: 29,
      name: 'Battery Park City',
      code: 'BPC',
      neighbours: 'TR, FD, TB',
      trainline: '',
    },
    {
      id: 30,
      name: 'Financial District',
      code: 'FD',
      neighbours: 'TR, BPC, CC, TBR, TB',
      trainline: '',
    },
    {
      id: 31,
      name: 'The Battery',
      code: 'TB',
      neighbours: 'BPC, FD',
      trainline: '',
    },
    {
      id: 32,
      name: 'Roosevelt Island',
      code: 'RVI',
      neighbours: '',
      trainline: '',
    },
    { id: 33, name: 'Astoria', code: 'AS', neighbours: 'LIC', trainline: '' },
    {
      id: 34,
      name: 'Long Island City',
      code: 'LIC',
      neighbours: 'AS, GP',
      trainline: '',
    },
    {
      id: 35,
      name: 'Greenpoint',
      code: 'GP',
      neighbours: 'LIC, WB, EWB',
      trainline: '',
    },
    {
      id: 36,
      name: 'Williamsburg',
      code: 'WB',
      neighbours: 'GP, EWB, BNY',
      trainline: '',
    },
    {
      id: 37,
      name: 'East Williamsburg',
      code: 'EWB',
      neighbours: 'GP, WB, BU, RI',
      trainline: '',
    },
    {
      id: 38,
      name: 'Ridgewood',
      code: 'RI',
      neighbours: 'EWB, BU',
      trainline: '',
    },
    {
      id: 39,
      name: 'Buswick',
      code: 'BU',
      neighbours: 'EWB, RI',
      trainline: '',
    },
    {
      id: 40,
      name: 'Dumbo',
      code: 'DU',
      neighbours: 'BNY, BRH, DBR',
      trainline: '',
    },
    {
      id: 41,
      name: 'Brooklyn Navy Yard',
      code: 'BNY',
      neighbours: 'WB, DU, DBR, CH, FG',
      trainline: '',
    },
    {
      id: 42,
      name: 'Brooklyn Heights',
      code: 'BRH',
      neighbours: 'DU, DBR, BH, CSW',
      trainline: '',
    },
    {
      id: 43,
      name: 'Downtown Brooklyn',
      code: 'DBR',
      neighbours: 'DU, BNY, BRH, BH, FG',
      trainline: '',
    },
    {
      id: 44,
      name: 'Fort Greene',
      code: 'FG',
      neighbours: 'BNY, DBR, CH, BH',
      trainline: '',
    },
    {
      id: 45,
      name: 'Clinton Hill',
      code: 'CH',
      neighbours: 'FG, BNY',
      trainline: '',
    },
    {
      id: 46,
      name: 'Columbia Street Waterfront District',
      code: 'CSW',
      neighbours: 'BRH, RH',
      trainline: '',
    },
    {
      id: 47,
      name: 'Boerum Hill',
      code: 'BH',
      neighbours: 'BRH, DBR, FG, PS, GO',
      trainline: '',
    },
    {
      id: 48,
      name: 'Gowanus',
      code: 'GO',
      neighbours: 'PS, BH',
      trainline: '',
    },
    {
      id: 49,
      name: 'Park Slope',
      code: 'PS',
      neighbours: 'GO, BH',
      trainline: '',
    },
    { id: 50, name: 'Red Hook', code: 'RH', neighbours: 'CSW', trainline: '' },
    {
      id: 51,
      name: 'Prospect Lefferts Gardens',
      code: 'PLG',
      neighbours: '',
      trainline: '',
    },
    { id: 52, name: 'Flushing', code: 'FL', neighbours: '', trainline: '' },
  ])
}
